### PR TITLE
Use Babel to transpile ES6 code during build

### PR DESCRIPTION
**Pull request by chrishein**
When trying to use html-colors in a React app created using [create-react-app](https://github.com/facebookincubator/create-react-app) I was unable to build the project as UglisfyJS choked with ES6 syntax used to export modules.

In order to use html-colros with UglifyJS I added Babel code transpilation during the build process, as recommended in this [SO answer](http://stackoverflow.com/a/42942214/250703).

I also moved source files into src/ folder, test into test/ and configured the build process to output to lib/.

### CODE REVIEW

**Comment by radiovisual** [comment]
What error are you getting while using this module with create-react-app? I just imported it into a react app using create-react-app `v1.3.0` and it works without any errors. Also, to be honest, I think that adding a transpile step to such a simple module is overkill. I am not even using that much ES6 syntax in this module. 

All we really need to do to get this module ES5-friendly, (which I am not opposed to) would be update this:

```js
module.exports = {
	names,
	hex,
	all,
	random
};
```

to this:

```js
module.exports = {
	names: names,
	hex: hex,
	all: all,
	random: random
};
```

because as far as I can tell, the object-shorthand is the only ES6 feature I am using in this module. So updating the code to a more ES5-friendly syntax would solve your problem, but wouldn't require adding a transpile step to such a simple module, and be less code/boilerplate to maintain over time.

Would you be opposed to removing the transpile step and instead just update the module to use ES5? I would be happier to merge that.

**Comment by chrishein** [comment]
Hi Michael! Thanks for your quick response. I agree that adding the transpiler is a bit too much and that rewriting the module.exports is more than enough.

Anyway, the error is only shown by trying to build the react app, and not by running in development mode.

I will submit a new pull request.

**Comment by chrishein** [comment]
I just remembered what pushed me to add the transpiler instead of just rewriting the module.exports.

ESlint through xo is enforcing the use of property shorthand.

screen shot 2017-04-23 at 4 11 36 pm

This can be fixed by overriding the default rules:

```
"xo": {
    "esnext": true,
    "rules": {
        "object-shorthand": ["error", "never"]
    }
  }
```

Would that be OK?

Thanks for your time and for considering this.

**Comment by radiovisual** [comment]
yeah, no problem, I am more concerned about universal appeal than linting concerns for small modules like this.

**Comment by radiovisual** [comment]
Just curious, It's your local XO that is complaining about object shorthand? Because XO (or this modules XO configuration) should not be making its way into your build step.

**Pull request closed without merging**
