### PR TITLE
Allow for Uppercase `htmlColors.hex("YELLOW"`

### PR DESCRIPTION
**Pull request by F1LT3R**
This PR allows for users to query the colors names in uppercase, for example: 

```js
htmlColors.hex('YELLOW')
htmlColors.hex('Yellow')
htmlColors.hex('YeLlOw')
```

### CODE REVIEW

**Comment by radiovisual** [comment]
Awesome! THANKS! 👍 Although I would prefer to keep the .lock file. What is your reason for removing it?

**Comment by F1LT3R** [comment]
I thought the lock file was only relevant to a codebase that's getting packaged and deployed to a server. Ie: let's make sure the code we publish does not change on us when we go to deploy, for security and stability reasons.

If someone was using your module and including it in a release to their site, then it would be their package lock that controls which package versions are used, I think. (I'm not sure if npm would go through all sub dependancies and check the package lock for each.)

Surely your users package lock is the source of truth, and not your module's package lock? 

Perhaps there's a hole in my understanding of how package locks work. What purpose does your package lock serve exactly?

**Comment by radiovisual** [comment]
I buy into the benefits of keeping the source of truth of the lock file in sync with the package.json file, even though I sometimes agree with the reasons why lock files are only good for apps, but not necessary for modules, I [read this article](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/) and it started making me see the bigger picture with the lock files. 

Most of the time, the lock files are a source of stress, because everybody feels differently about them, but I think that since most of the early headaches with the files have disappeared, it is better to keep them then to ignore them. They *are* a source of truth for modules, as long as they are always up-to-date.

**Comment by F1LT3R** [comment]
Good to know. Thanks for the article @radiovisual

**Comment by radiovisual** [comment]
This is now available in the published version `0.0.6`

**Pull request merged**
